### ISSUE TITLE
How to use the wrapper on a windows machine?

### ISSUE THREAD

**Issue by Boraly** [taikamurmeli/Doc2VecC_python#1]
Hello, 

I want to use this wrapper on a windows machine, but the library pthreads in the C-implementation is not avaibale on windows, only on linux. Do you know how I could still use it on windows?

Thank you a lot!

**Comment by sjsarsa** [comment]
Hi!

A surefire way would be to use [WSL](https://learn.microsoft.com/en-us/windows/wsl/install) for running Linux on your Windows.
That would of course require using Linux.

Anyhow, I can check when I have more free time if I can make it work with e.g. https://github.com/GerHobbelt/pthread-win32

**Comment by Boraly** [comment]
Thank you for the the answer. I will try to use WSL.
But please keep me updated if you managed to get it running on windows.

Thanks in advance,
Boraly
